import type { TimelineEntry } from "@/features/customers/services/timeline/types";

const TIMELINES: Record<string, TimelineEntry[]> = {
  "1": [
    {
      id: "tl-1-01",
      customerId: "1",
      type: "mail",
      date: "2026-07-07",
      time: "09:14",
      title: "Anfrage Büroausstattung",
      description: "Thomas Müller fragt nach verbindlichem Angebot für 45 Arbeitsplätze.",
      source: "Gmail",
      status: "neu",
      helpyDetected: true,
    },
    {
      id: "tl-1-02",
      customerId: "1",
      type: "helpy",
      date: "2026-07-07",
      time: "09:15",
      title: "Vorgang vorbereitet",
      description: "HELPY hat Kunde, Baustelle und Offerte für Weber & Co. vorbereitet.",
      source: "HELPY",
      status: "erledigt",
      helpyDetected: true,
    },
    {
      id: "tl-1-03",
      customerId: "1",
      type: "angebot",
      date: "2026-07-06",
      time: "16:30",
      title: "Angebot A-2026-0147 erstellt",
      description: "Summe 68.420 € · Entwurf zur Freigabe bereit.",
      source: "HELPY Angebote",
      status: "offen",
    },
    {
      id: "tl-1-04",
      customerId: "1",
      type: "whatsapp",
      date: "2026-07-06",
      time: "11:20",
      title: "Kurze Rückfrage Lieferzeit",
      description: "Thomas wünscht Express-Lieferung bis Freitag.",
      source: "WhatsApp",
      status: "erledigt",
    },
    {
      id: "tl-1-05",
      customerId: "1",
      type: "telefon",
      date: "2026-06-28",
      time: "11:00",
      title: "Telefonat Rückfrage Lieferung",
      description: "15 Min. · Lieferfenster und Montage besprochen.",
      source: "Telefon",
      status: "erledigt",
    },
    {
      id: "tl-1-06",
      customerId: "1",
      type: "termin",
      date: "2026-06-25",
      time: "14:00",
      title: "Besprechung Angebot",
      description: "Vor-Ort-Termin bei Weber & Co. in München.",
      source: "Kalender",
      status: "bestaetigt",
    },
    {
      id: "tl-1-07",
      customerId: "1",
      type: "dokument",
      date: "2026-06-20",
      time: "10:00",
      title: "Grundriss Büro Neu.pdf",
      description: "Projektunterlage dem Vorgang zugeordnet.",
      source: "Dokumente",
      status: "erledigt",
    },
    {
      id: "tl-1-08",
      customerId: "1",
      type: "rechnung",
      date: "2026-06-18",
      time: "09:00",
      title: "Rechnung RE-2026-0312 bezahlt",
      description: "3.420 € · Zahlungseingang verbucht.",
      source: "Rechnungen",
      status: "erledigt",
    },
    {
      id: "tl-1-09",
      customerId: "1",
      type: "vertrag",
      date: "2026-06-10",
      time: "15:30",
      title: "Rahmenvertrag 2026 unterzeichnet",
      description: "Wartungskonditionen für Bestandskunde aktualisiert.",
      source: "Dokumente",
      status: "bestaetigt",
    },
  ],
  "2": [
    {
      id: "tl-2-01",
      customerId: "2",
      type: "mail",
      date: "2026-07-05",
      time: "14:22",
      title: "Terminvorschlag Q2-Planung",
      description: "Sandra schlägt Dienstag 14:00 Uhr vor.",
      source: "Outlook",
      status: "offen",
      helpyDetected: true,
    },
    {
      id: "tl-2-02",
      customerId: "2",
      type: "termin",
      date: "2026-07-08",
      time: "14:00",
      title: "Q2-Planung · Besprechung",
      description: "Teams-Call mit Sandra Klein.",
      source: "Kalender",
      status: "bestaetigt",
    },
    {
      id: "tl-2-03",
      customerId: "2",
      type: "website",
      date: "2026-06-15",
      time: "09:00",
      title: "Erstanfrage über Kontaktformular",
      description: "Interesse an Wartungsvertrag für 3 Standorte.",
      source: "Website",
      status: "erledigt",
      helpyDetected: true,
    },
    {
      id: "tl-2-04",
      customerId: "2",
      type: "telefon",
      date: "2026-06-20",
      time: "10:30",
      title: "Erstgespräch Wartungsvertrag",
      description: "22 Min. · Bedarf und Budgetrahmen geklärt.",
      source: "Telefon",
      status: "erledigt",
    },
  ],
  "3": [
    {
      id: "tl-3-01",
      customerId: "3",
      type: "immoscout24",
      date: "2026-07-06",
      time: "08:45",
      title: "Neue Anfrage Gewerbeobjekt Nord",
      description: "Besichtigungswunsch für Projekt Nord — 420 m² Fläche.",
      source: "ImmoScout24.ch",
      status: "neu",
      helpyDetected: true,
    },
    {
      id: "tl-3-02",
      customerId: "3",
      type: "helpy",
      date: "2026-07-06",
      time: "08:46",
      title: "Interessent und Besichtigung vorbereitet",
      description: "HELPY hat Interessent angelegt und Terminentwurf erstellt.",
      source: "HELPY",
      status: "erledigt",
      helpyDetected: true,
    },
    {
      id: "tl-3-03",
      customerId: "3",
      type: "termin",
      date: "2026-07-06",
      time: "14:00",
      title: "Immobilienbesichtigung Projekt Nord",
      description: "Vor-Ort-Termin mit Markus Richter.",
      source: "Kalender",
      status: "bestaetigt",
    },
    {
      id: "tl-3-04",
      customerId: "3",
      type: "mail",
      date: "2026-07-04",
      time: "11:30",
      title: "Projektunterlagen angefordert",
      description: "Grundrisse und Fotos für das Objekt Nord.",
      source: "Gmail",
      status: "versendet",
    },
    {
      id: "tl-3-05",
      customerId: "3",
      type: "angebot",
      date: "2026-06-28",
      time: "16:00",
      title: "Angebot A-2026-0820 versendet",
      description: "Summe 45.600 € · Rückmeldung ausstehend.",
      source: "HELPY Angebote",
      status: "versendet",
    },
    {
      id: "tl-3-06",
      customerId: "3",
      type: "dokument",
      date: "2026-06-25",
      time: "09:15",
      title: "Exposé Projekt Nord.pdf",
      description: "Exposé für Besichtigung vorbereitet.",
      source: "Dokumente",
      status: "erledigt",
    },
  ],
  "4": [
    {
      id: "tl-4-01",
      customerId: "4",
      type: "website",
      date: "2026-07-06",
      time: "08:30",
      title: "Erstkontakt über Website",
      description: "Lisa Wagner — Interesse an Büroausstattung für 25 Mitarbeiter.",
      source: "Website",
      status: "neu",
      helpyDetected: true,
    },
    {
      id: "tl-4-02",
      customerId: "4",
      type: "helpy",
      date: "2026-07-06",
      time: "08:31",
      title: "Lead qualifiziert",
      description: "HELPY hat Interessent angelegt und Erstgespräch vorgeschlagen.",
      source: "HELPY",
      status: "erledigt",
      helpyDetected: true,
    },
    {
      id: "tl-4-03",
      customerId: "4",
      type: "mail",
      date: "2026-07-06",
      time: "08:30",
      title: "LinkedIn-Nachricht erfasst",
      description: "Erstkontakt von Lisa Wagner als Mail im Vorgang.",
      source: "Gmail",
      status: "offen",
    },
  ],
  "5": [
    {
      id: "tl-5-01",
      customerId: "5",
      type: "vertrag",
      date: "2026-06-15",
      time: "10:00",
      title: "Rahmenvertrag 2026 verlängert",
      description: "Jährliche Verlängerung mit Dr. Hans Bauer.",
      source: "Dokumente",
      status: "bestaetigt",
    },
    {
      id: "tl-5-02",
      customerId: "5",
      type: "rechnung",
      date: "2026-06-01",
      time: "09:00",
      title: "Quartalsrechnung Q2 versendet",
      description: "12.400 € · Zahlungsziel 30 Tage.",
      source: "Rechnungen",
      status: "versendet",
    },
    {
      id: "tl-5-03",
      customerId: "5",
      type: "termin",
      date: "2026-05-20",
      time: "11:00",
      title: "Jahresreview",
      description: "Bestandskunden-Gespräch in Stuttgart.",
      source: "Kalender",
      status: "erledigt",
    },
  ],
};

export const MOCK_CUSTOMER_TIMELINES: TimelineEntry[] = Object.values(
  TIMELINES
).flat();

export function getTimelineForCustomer(customerId: string): TimelineEntry[] {
  return TIMELINES[customerId] ?? [];
}

export function getTimelineEntryCount(customerId: string): number {
  return getTimelineForCustomer(customerId).length;
}
