import type { DocumentTemplate } from "@/features/documents/services/types";

export const MOCK_TEMPLATES: DocumentTemplate[] = [
  {
    id: "tpl-re-expose",
    typeId: "expose",
    skill: "real-estate",
    label: "Exposé",
    description: "Professionelles Objekt-Exposé mit Eckdaten, Lage und Ausstattung.",
    category: "vorlage",
  },
  {
    id: "tpl-re-besichtigungstermin",
    typeId: "besichtigungstermin",
    skill: "real-estate",
    label: "Besichtigungstermin",
    description:
      "Terminbestätigung mit Datum, Adresse, Ansprechpartner und Checkliste.",
    category: "vorlage",
  },
  {
    id: "tpl-re-besichtigung",
    typeId: "besichtigungsprotokoll",
    skill: "real-estate",
    label: "Besichtigungsprotokoll",
    description: "Protokoll für Besichtigungstermine mit Interessenten-Feedback.",
    category: "vorlage",
  },
  {
    id: "tpl-re-reservation",
    typeId: "reservationsbestaetigung",
    skill: "real-estate",
    label: "Reservationsbestätigung",
    description: "Bestätigung einer Objekt-Reservation inkl. Konditionen.",
    category: "vorlage",
  },
  {
    id: "tpl-re-kaufinteressent",
    typeId: "kaufinteressenten-zusammenfassung",
    skill: "real-estate",
    label: "Kaufinteressenten-Zusammenfassung",
    description: "Übersicht über Interessentenstatus, Budget und nächste Schritte.",
    category: "vorlage",
  },
  {
    id: "tpl-hw-offerte",
    typeId: "offerte",
    skill: "construction",
    label: "Offerte",
    description: "Detaillierte Offerte mit Positionen, Material und Arbeitszeit.",
    category: "vorlage",
  },
  {
    id: "tpl-hw-arbeitsrapport",
    typeId: "arbeitsrapport",
    skill: "construction",
    label: "Arbeitsrapport",
    description: "Tagesrapport für Baustelle oder Serviceeinsatz.",
    category: "vorlage",
  },
  {
    id: "tpl-hw-material",
    typeId: "materialliste",
    skill: "construction",
    label: "Materialliste",
    description: "Materialbedarf mit Mengen, Einheiten und Lieferstatus.",
    category: "vorlage",
  },
  {
    id: "tpl-hw-auftrag",
    typeId: "auftragsbestaetigung",
    skill: "construction",
    label: "Auftragsbestätigung",
    description: "Bestätigung des erteilten Auftrags mit Terminen und Leistungsumfang.",
    category: "vorlage",
  },
  {
    id: "tpl-cl-angebot",
    typeId: "angebot",
    skill: "consulting-legal",
    label: "Angebot",
    description: "Beratungs- oder Mandatsangebot mit Leistungsbeschreibung.",
    category: "vorlage",
  },
  {
    id: "tpl-cl-mandat",
    typeId: "mandatsbestaetigung",
    skill: "consulting-legal",
    label: "Mandatsbestätigung",
    description: "Formelle Mandatsübernahme mit Umfang und Vergütung.",
    category: "vorlage",
  },
  {
    id: "tpl-cl-vollmacht",
    typeId: "vollmacht",
    skill: "consulting-legal",
    label: "Vollmacht",
    description: "Vollmacht zur Vertretung in definiertem Mandatsbereich.",
    category: "vorlage",
  },
  {
    id: "tpl-cl-protokoll",
    typeId: "beratungsprotokoll",
    skill: "consulting-legal",
    label: "Beratungsprotokoll",
    description: "Protokoll eines Beratungsgesprächs mit Vereinbarungen.",
    category: "vorlage",
  },
  {
    id: "tpl-cl-fristen",
    typeId: "fristenuebersicht",
    skill: "consulting-legal",
    label: "Fristenübersicht",
    description: "Übersicht relevanter Fristen und Handlungsschritte.",
    category: "vorlage",
  },
];
