import type { PreparedDocument } from "@/features/documents/services/types";

export const MOCK_DOCUMENTS: PreparedDocument[] = [
  {
    id: "doc-1",
    typeId: "expose",
    skill: "real-estate",
    typeLabel: "Exposé",
    title: "Exposé — Penthouse Leopoldstraße",
    customer: "ImmoService Richter",
    vorgangId: "techstart-neu",
    vorgangTitle: "Verkauf Penthouse Leopoldstraße",
    status: "zur-pruefung",
    category: "helpy-vorbereitet",
    lastEdited: "Heute, 09:42",
    helpyHint: "Objektdaten und Bilder sind eingepflegt — bitte Preisangabe und Energieausweis prüfen.",
    preparedByHelpy: true,
    previewSections: [
      {
        heading: "Objektübersicht",
        content:
          "Penthouse-Wohnung, 142 m² Wohnfläche, 4 Zimmer, Südbalkon, Aufzug, Tiefgaragenstellplatz. Baujahr 2018, Energieeffizienzklasse B.",
      },
      {
        heading: "Lage & Ausstattung",
        content:
          "Ruhige Seitenstraße in Schwabing, 5 Min. zur U3. Hochwertige Einbauküche, Fußbodenheizung, Smart-Home-Basisausstattung.",
      },
      {
        heading: "Angebotspreis",
        content: "Kaufpreis: 1.290.000 EUR (Provision gemäß Vereinbarung).",
      },
    ],
  },
  {
    id: "doc-2a",
    typeId: "besichtigungstermin",
    skill: "real-estate",
    typeLabel: "Besichtigungstermin",
    title: "Besichtigungstermin — Industriestraße 12",
    customer: "Thomas Müller",
    vorgangId: "weber-angebot",
    vorgangTitle: "Gewerbeobjekt Besichtigung",
    status: "freigegeben",
    category: "helpy-vorbereitet",
    lastEdited: "Heute, 10:05",
    helpyHint:
      "Terminbestätigung ist vorbereitet — bitte Anfahrtshinweis und Ansprechpartner prüfen.",
    preparedByHelpy: true,
    previewSections: [
      {
        heading: "Termindaten",
        content: "Datum: 12.07.2026, 18:30 Uhr · Dauer: 45 Minuten",
      },
      {
        heading: "Treffpunkt",
        content: "Gewerbeeinheit Industriestraße 12, 80331 München",
      },
      {
        heading: "Anfahrt",
        content:
          "Eingang über den Innenhof. Parkplätze in der Tiefgarage Haus B, Besucherplätze 1–3.",
      },
      {
        heading: "Hinweise",
        content:
          "Bitte pünktlich erscheinen. Bei Verspätung kurz unter der angegebenen Nummer melden.",
      },
    ],
  },
  {
    id: "doc-2",
    typeId: "besichtigungsprotokoll",
    skill: "real-estate",
    typeLabel: "Besichtigungsprotokoll",
    title: "Besichtigungsprotokoll — Weber & Co.",
    customer: "Weber & Co. GmbH",
    vorgangId: "weber-angebot",
    vorgangTitle: "Gewerbeobjekt Besichtigung",
    status: "entwurf",
    category: "entwurf",
    lastEdited: "Gestern, 16:20",
    helpyHint: "Termin und Anwesende sind erfasst — Feedback des Interessenten bitte ergänzen.",
    preparedByHelpy: false,
    previewSections: [
      {
        heading: "Termindaten",
        content: "Datum: 05.07.2026, 18:30 Uhr · Objekt: Gewerbeeinheit Industriestraße 12",
      },
      {
        heading: "Teilnehmer",
        content: "Thomas Müller (Weber & Co.), Anna Richter (ImmoService Richter)",
      },
      {
        heading: "Rückmeldung",
        content: "Interessent wünscht zweite Besichtigung mit technischem Gutachter.",
      },
    ],
  },
  {
    id: "doc-3",
    typeId: "reservationsbestaetigung",
    skill: "real-estate",
    typeLabel: "Reservationsbestätigung",
    title: "Reservation — Eigentumswohnung Sendling",
    customer: "Familie Hoffmann",
    status: "freigegeben",
    category: "fertig",
    lastEdited: "03.07.2026",
    helpyHint: "Reservationsfrist läuft in 5 Tagen ab — Nachverfolgung empfohlen.",
    preparedByHelpy: true,
    previewSections: [
      {
        heading: "Reserviertes Objekt",
        content: "3-Zimmer-Wohnung, 78 m², Sendlinger Straße 42, 81371 München",
      },
      {
        heading: "Konditionen",
        content: "Reservationsgebühr: 5.000 EUR · Reservierungsdauer: 14 Tage ab Unterzeichnung",
      },
    ],
  },
  {
    id: "doc-4",
    typeId: "offerte",
    skill: "construction",
    typeLabel: "Offerte",
    title: "Offerte — Sanitärinstallation Neubau",
    customer: "Berger Bau GmbH",
    vorgangId: "schmidt-angebot",
    vorgangTitle: "Sanitärinstallation Wohnanlage",
    status: "zur-pruefung",
    category: "helpy-vorbereitet",
    lastEdited: "Heute, 08:15",
    helpyHint: "Positionen und Materialkosten sind berechnet — Vor-Ort-Termin noch nicht bestätigt.",
    preparedByHelpy: true,
    previewSections: [
      {
        heading: "Leistungsumfang",
        content: "24× Komplett-Badezimmer Installation (Standard), inkl. Armaturen und Anschlüsse.",
      },
      {
        heading: "Kalkulation",
        content: "Material: 48.200 EUR · Arbeitszeit: 28.800 EUR · Projektleitung: 6.500 EUR",
      },
      {
        heading: "Gültigkeit",
        content: "Offerte gültig bis 31.07.2026. Zahlungsziel: 14 Tage netto.",
      },
    ],
  },
  {
    id: "doc-5",
    typeId: "materialliste",
    skill: "construction",
    typeLabel: "Materialliste",
    title: "Materialliste — Fassadensanierung",
    customer: "ImmoService Richter",
    status: "entwurf",
    category: "entwurf",
    lastEdited: "04.07.2026",
    helpyHint: "Mengen basieren auf Flächenangabe — bitte vor Bestellung vor Ort verifizieren.",
    preparedByHelpy: true,
    previewSections: [
      {
        heading: "Materialpositionen",
        content: "Fassadenfarbe Premium: 420 L · Grundierung: 180 L · Gerüstmaterial: 1 Set",
      },
      {
        heading: "Lieferstatus",
        content: "3 Positionen bestellt, 1 Position noch offen (Lieferzeit 5–7 Werktage).",
      },
    ],
  },
  {
    id: "doc-6",
    typeId: "arbeitsrapport",
    skill: "construction",
    typeLabel: "Arbeitsrapport",
    title: "Arbeitsrapport — Heizungswartung Schmidt",
    customer: "Schmidt GmbH",
    status: "gesendet",
    category: "fertig",
    lastEdited: "28.06.2026",
    helpyHint: "Rapport wurde versendet — Kundenunterschrift liegt vor.",
    preparedByHelpy: false,
    previewSections: [
      {
        heading: "Einsatz",
        content: "Datum: 27.06.2026 · Dauer: 3,5 Std. · Techniker: M. Bauer",
      },
      {
        heading: "Durchgeführte Arbeiten",
        content: "Jährliche Wartung Heizungsanlage, Brenner gereinigt, Sicherheitsprüfung durchgeführt.",
      },
    ],
  },
  {
    id: "doc-7",
    typeId: "angebot",
    skill: "consulting-legal",
    typeLabel: "Angebot",
    title: "Angebot — Steuerberatung Finanzamt",
    customer: "Finanzamt München",
    vorgangId: "finanzamt-steuer",
    vorgangTitle: "Steuerliche Sonderprüfung",
    status: "zur-pruefung",
    category: "helpy-vorbereitet",
    lastEdited: "Heute, 10:05",
    helpyHint: "Leistungsbeschreibung und Stundensätze sind eingetragen — Mandatsumfang bitte final abstimmen.",
    preparedByHelpy: true,
    previewSections: [
      {
        heading: "Leistungsumfang",
        content: "Begleitung bei steuerlicher Sonderprüfung, Dokumentenprüfung, Stellungnahmen.",
      },
      {
        heading: "Vergütung",
        content: "Stundensatz: 280 EUR · Geschätzter Aufwand: 40–60 Stunden",
      },
    ],
  },
  {
    id: "doc-8",
    typeId: "mandatsbestaetigung",
    skill: "consulting-legal",
    typeLabel: "Mandatsbestätigung",
    title: "Mandatsbestätigung — TechStart AG",
    customer: "TechStart AG",
    status: "freigegeben",
    category: "fertig",
    lastEdited: "01.07.2026",
    helpyHint: "Mandatsvertrag liegt unterschriftsreif vor.",
    preparedByHelpy: true,
    previewSections: [
      {
        heading: "Mandatsgegenstand",
        content: "Beratung zu KI-Compliance und Datenschutz im Pilotprojekt HELPY Office KI.",
      },
      {
        heading: "Vergütung",
        content: "Pauschalhonorar: 12.500 EUR zzgl. MwSt., zahlbar in 2 Raten.",
      },
    ],
  },
  {
    id: "doc-9",
    typeId: "fristenuebersicht",
    skill: "consulting-legal",
    typeLabel: "Fristenübersicht",
    title: "Fristenübersicht — Q3 Mandate",
    customer: "Intern",
    status: "entwurf",
    category: "entwurf",
    lastEdited: "06.07.2026",
    helpyHint: "3 Fristen in den nächsten 14 Tagen — bitte Kalendertermine prüfen.",
    preparedByHelpy: true,
    previewSections: [
      {
        heading: "Dringende Fristen",
        content: "10.07. — Stellungnahme Finanzamt · 14.07. — Vertragsverlängerung TechStart · 18.07. — Einspruchsfrist Weber",
      },
      {
        heading: "Empfehlung",
        content: "Fristen im Kalender sichern und Verantwortliche zuweisen.",
      },
    ],
  },
  {
    id: "doc-10",
    typeId: "beratungsprotokoll",
    skill: "consulting-legal",
    typeLabel: "Beratungsprotokoll",
    title: "Beratungsprotokoll — Erstgespräch Weber",
    customer: "Weber & Co. GmbH",
    vorgangId: "weber-angebot",
    vorgangTitle: "Erstberatung Gewerbemietrecht",
    status: "entwurf",
    category: "helpy-vorbereitet",
    lastEdited: "Gestern, 11:30",
    helpyHint: "Gesprächsinhalte sind zusammengefasst — Vereinbarungen bitte bestätigen lassen.",
    preparedByHelpy: true,
    previewSections: [
      {
        heading: "Gesprächspartner",
        content: "Thomas Müller (Weber & Co.), Berater: Kanzlei Partner",
      },
      {
        heading: "Besprochene Punkte",
        content: "Mietvertragsprüfung, Kündigungsfristen, Option auf Verlängerung.",
      },
      {
        heading: "Nächste Schritte",
        content: "Vertragsentwurf bis 12.07. · Zweites Gespräch nach Durchsicht.",
      },
    ],
  },
  {
    id: "doc-11",
    typeId: "kaufinteressenten-zusammenfassung",
    skill: "real-estate",
    typeLabel: "Kaufinteressenten-Zusammenfassung",
    title: "Interessenten — Penthouse Leopoldstraße",
    customer: "3 Interessenten",
    status: "entwurf",
    category: "helpy-vorbereitet",
    lastEdited: "Heute, 07:50",
    helpyHint: "Interessent A hat höchste Kaufbereitschaft — Follow-up empfohlen.",
    preparedByHelpy: true,
    previewSections: [
      {
        heading: "Interessentenstatus",
        content: "A: Finanzierung bestätigt · B: Besichtigung 2 ausstehend · C: Erstkontakt",
      },
      {
        heading: "Budgetrahmen",
        content: "1,1–1,4 Mio. EUR · Bevorzugte Besichtigungszeit: Abends",
      },
    ],
  },
  {
    id: "doc-12",
    typeId: "auftragsbestaetigung",
    skill: "construction",
    typeLabel: "Auftragsbestätigung",
    title: "Auftragsbestätigung — Wartungsvertrag",
    customer: "Schmidt GmbH",
    status: "gesendet",
    category: "fertig",
    lastEdited: "15.06.2026",
    helpyHint: "Auftrag bestätigt — Ersttermin im Kalender hinterlegt.",
    preparedByHelpy: true,
    previewSections: [
      {
        heading: "Auftragsumfang",
        content: "Jährlicher Wartungsvertrag Heizungsanlage, 12 Monate Laufzeit.",
      },
      {
        heading: "Termine",
        content: "Erstwartung: 20.08.2026 · Vertragsbeginn: 01.07.2026",
      },
    ],
  },
];
